# Generated by Django 4.2.7 on 2025-07-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickstreamevent',
            name='event_name',
            field=models.CharField(choices=[('page_view', 'Page View'), ('click', 'Click'), ('video_play', 'Video Play'), ('video_pause', 'Video Pause'), ('video_complete', 'Video Complete'), ('quiz_attempt', 'Quiz Attempt'), ('quiz_submit', 'Quiz Submit'), ('text_read', 'Text Read'), ('login', 'Login'), ('logout', 'Logout'), ('registration', 'Registration')], max_length=50),
        ),
    ]
