# Generated by Django 4.2.7 on 2025-09-30 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0004_livequiz_quizanalytics_quizanswer_quizparticipant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_answer',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True/False'), ('subjective', 'Subjective')], default='mcq', max_length=15),
        ),
        migrations.CreateModel(
            name='SubjectiveAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjective_answers', to='learning_app.quizparticipant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_app.quizquestion')),
            ],
            options={
                'unique_together': {('participant', 'question')},
            },
        ),
    ]
