# Generated by Django 4.2.7 on 2025-09-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0005_alter_quizquestion_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=15),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
