# Generated by Django 4.2.7 on 2025-10-09 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0006_quizquestion_approval_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('poll_type', models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('text_response', 'Text Response'), ('rating_scale', 'Rating Scale (1-5)'), ('yes_no', 'Yes/No')], default='single_choice', max_length=20)),
                ('poll_code', models.CharField(blank=True, max_length=8, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('ended', 'Ended')], default='draft', max_length=10)),
                ('is_anonymous', models.BooleanField(default=False, help_text='If True, responses are anonymous')),
                ('allow_multiple_responses', models.BooleanField(default=False, help_text='Allow same person to respond multiple times')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_app.teacherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='learning_app.poll')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PollAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_responses', models.IntegerField(default=0)),
                ('response_distribution', models.JSONField(default=dict, help_text='Distribution of responses by option')),
                ('average_rating', models.FloatField(default=0.0, help_text='Average rating for rating polls')),
                ('response_timeline', models.JSONField(default=list, help_text='Response timeline data')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='learning_app.poll')),
            ],
        ),
        migrations.CreateModel(
            name='PollResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('selected_options', models.JSONField(default=list, help_text='List of selected option IDs for choice polls')),
                ('text_response', models.TextField(blank=True, help_text='Text response for text polls')),
                ('rating_value', models.IntegerField(blank=True, help_text='Rating value (1-5) for rating polls', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='learning_app.poll')),
            ],
            options={
                'unique_together': {('poll', 'ip_address')},
            },
        ),
    ]
