# Generated by Django 4.2.7 on 2025-10-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0007_poll_polloption_pollanalytics_pollresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollanalytics',
            name='word_cloud_data',
            field=models.JSONField(default=dict, help_text='Word frequencies for text response polls'),
        ),
        migrations.AddField(
            model_name='pollanalytics',
            name='word_cloud_generated_at',
            field=models.DateTimeField(blank=True, help_text='When word cloud was last generated', null=True),
        ),
    ]
