# Generated by Django 4.2.7 on 2025-11-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0008_pollanalytics_word_cloud_data_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pollresponse',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='pollresponse',
            index=models.Index(fields=['poll', 'ip_address'], name='learning_ap_poll_id_f72790_idx'),
        ),
    ]
