# Generated by Django 4.2.7 on 2025-11-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0009_alter_pollresponse_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollanalytics',
            name='word_cloud_image',
            field=models.TextField(blank=True, help_text='Base64 encoded word cloud image', null=True),
        ),
    ]
